basePath: /api/v1
definitions:
  code.Failure:
    properties:
      code:
        description: 业务码
        type: integer
      message:
        description: 描述信息
        type: string
    type: object
  img.createAsyncRequest:
    type: object
  img.createAsyncResponse:
    type: object
  img.createSyncRequest:
    type: object
  img.createSyncResponse:
    type: object
  img.taskListRequest:
    type: object
  img.taskListResponse:
    type: object
  img.templateListRequest:
    type: object
  img.templateListResponse:
    type: object
  video.createAsyncRequest:
    type: object
  video.createAsyncResponse:
    type: object
  video.createSyncRequest:
    type: object
  video.createSyncResponse:
    type: object
  video.taskListRequest:
    type: object
  video.taskListResponse:
    type: object
  video.templateListRequest:
    type: object
  video.templateListResponse:
    type: object
info:
  contact: {}
paths:
  /api/img/createAsync:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 合成素材(异步)
      parameters:
      - description: 请求信息
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/img.createAsyncRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/img.createAsyncResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      summary: 合成素材(异步)
      tags:
      - API.img
  /api/img/createSync:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 合成素材(同步)
      parameters:
      - description: 请求信息
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/img.createSyncRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/img.createSyncResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      summary: 合成素材(同步)
      tags:
      - API.img
  /api/img/task:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 查询视频合成结果接口
      parameters:
      - description: 请求信息
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/img.taskListRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/img.taskListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      summary: 查询视频合成结果接口
      tags:
      - API.img
  /api/img/template:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 视频模板列表接口
      parameters:
      - description: 请求信息
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/img.templateListRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/img.templateListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      summary: 视频模板列表接口
      tags:
      - API.img
  /api/video/createAsync:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 合成素材(异步)
      parameters:
      - description: 请求信息
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/video.createAsyncRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/video.createAsyncResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      summary: 合成素材(异步)
      tags:
      - API.video
  /api/video/createSync:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 合成素材(同步)
      parameters:
      - description: 请求信息
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/video.createSyncRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/video.createSyncResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      summary: 合成素材(同步)
      tags:
      - API.video
  /api/video/task:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 查询视频合成结果接口
      parameters:
      - description: 请求信息
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/video.taskListRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/video.taskListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      summary: 查询视频合成结果接口
      tags:
      - API.video
  /api/video/template:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 视频模板列表接口
      parameters:
      - description: 请求信息
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/video.templateListRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/video.templateListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      summary: 视频模板列表接口
      tags:
      - API.video
  /example/helloworld:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
swagger: "2.0"
